### ISSUE TITLE
Trailing comma in "hints" with json output

### ISSUE THREAD

**Issue by Jokler** [Sweets/tiramisu#18]
Prettified Output:
```json
{
    "app_name": "Telegram Desktop",
    "app_icon": "",
    "replaces_id": 0,
    "timeout": -1,
    "hints": {
        "category": "im.received",
        "desktop-entry": "telegramdesktop",
    },
    "actions": {},
    "summary": "...",
    "body": "..."
}
```
There should not be a comma after the "desktop-entry" hint.

**Comment by MarkusG** [comment]
This happens because the `hints_output_iterator()` function skips values of unknown type, but doesn't skip printing the comma before them. There's some value of unknown type after the `desktop-entry` hint, so it prints a comma in anticipation of that value. Because the value is of unknown type, the iterator skips it, leaving the comma alone. Working on a PR now.
