### ISSUE TITLE
Output with markup tags

### ISSUE THREAD

**Issue by toniz4** [Sweets/tiramisu#24]
In the desktop notifications specs it says that the client should be capable of outputting a simple markup, and if not it should be filtered. So tiramisu filters them? If yes there is a way to disable that?

**Comment by Sweets** [comment]
tiramisu isn't an end client, though.

I mean, strictly speaking, you would be correct in saying that, because as far as desktop notification spec is concerned, it is the client. More realistically though, it's just a transient. More like a bus to the end client. That being the case though, markup outputting and/or filtering is done at the discretion of the end point, not the transient.
