### ISSUE TITLE
Vala Rewrite

### ISSUE THREAD

**Issue by Sweets** [Sweets/tiramisu#34]
Any issues with the Vala rewrite should be reported here.

Some testing is required, in particular
- Notifications that provide images (#27)
- JSON output does need to be verified (#31). In my testing it was fine, but some realistic application would be more appropriate.
- ...Everything else? While most things should be fine, additional testing and realistic application is always necessary. And unfortunately, I can't supplement that all myself.

**Comment by Sweets** [comment]
> At the moment, it doesn't seem to compile:
> 
> ```
>  $ ~/Downloads/tiramisu make && make install
> valac --pkg gio-2.0 src/notification.vala src/dbus.vala src/tiramisu.vala -o tiramisu
> make: valac: No such file or directory
> make: *** [Makefile:16: tiramisu] Error 127
> ```
> 
> The same from AUR...
> 
> EDIT: Turned out we needed `vala` as dependency. After that seems to work fine. Perhaps, this dependency should be added to aur built...

Vala is a new dependency with the rewrite. It should be added as a dependency on the AUR, but unfortunately I do not package tiramisu (much less for the AUR). What I'd suggest in this specific case is leaving a comment on the AUR page and hope that the maintainer will add it.

**Comment by vredesbyyrd** [comment]
I may have ran into a small issue with the `vala` rewrite. It seems some `hints` are wrapped in single quotes.  

tiramisu cmd: `tiramisu`

**vala rewrite:** 

desktop-entry='rsync',urgency=0x01 

**C versions:** 

desktop-entry=rsync,urgency=0x01

I only noticed it because I am serializing notifications as `lua` tables to later be interacted with from `rofi`,  and some hints are quoted like `"'foo'"`: 

```lua
  ["1634794309016"]={
    actions="default,",
    body="[JLErvin/berry] workspaces only on primary display (#151)",
    hints={
      ["desktop-entry"]="'org.gnome.Geary'",
      urgency="0x01"
    },
    id="0",
    source="Geary",
    summary="Josh Ervin",
    unread=true,
    icon="/home/clu/.cache/rofi_notification/mail-message-new-symbolic.png"
  }
```

Probably not a big deal, and for all i know it is purposeful. I am just making note of it in case its not intentional.

**Comment by Sweets** [comment]
> I may have ran into a small issue with the `vala` rewrite. It seems some `hints` are wrapped in single quotes.
> 
> tiramisu cmd: `tiramisu`
> 
> **vala rewrite:**
> 
> desktop-entry='rsync',urgency=0x01
> 
> **C versions:**
> 
> desktop-entry=rsync,urgency=0x01
> 
> I only noticed it because I am serializing notifications as `lua` tables to later be interacted with from `rofi`, and some hints are quoted like `"'foo'"`:
> 
> ```lua
>   ["1634794309016"]={
>     actions="default,",
>     body="[JLErvin/berry] workspaces only on primary display (#151)",
>     hints={
>       ["desktop-entry"]="'org.gnome.Geary'",
>       urgency="0x01"
>     },
>     id="0",
>     source="Geary",
>     summary="Josh E",
>     unread=true,
>     icon="/home/clu/.cache/rofi_notification/mail-message-new-symbolic.png"
>   }
> ```
> 
> Probably not a big deal, and for all i know it is purposeful. I am just making note of it in case its not intentional.

So this was an intended change. Reason being is that strings passed as a hint have no specification (as of 1.2 spec anyways) saying that the strings can't have quotes in them.

There is specification for the standardized hints, for example `desktop-entry`, but other than that, you can in theory create any hint you want to further supply the receiving program with information. So you can make a hint that is say, `my-custom-hint`, with a content of `some 'string' here`. Which at that point would be output to tiramisu as `'some \'string\' here'`.

**Comment by vredesbyyrd** [comment]
Okay, that all makes sense. And I appreciate the reasoning :)

**Comment by vredesbyyrd** [comment]
Tiramisu is not receiving notifications from firefox, instead the browser creates is own popup. Same/similar to issue #20 perhaps. I have not tested on chrome. 

I see [here](https://github.com/Sweets/tiramisu/blob/890966a18f9f9e139fa7df9080363d09de32e345/src/dbus.vala#L13-L16) that `GetCapabilities` is implemented. Maybe its because `GetCapabilities` only returns `body` and the notification requires more, eg `actions`? That's a total guess.  

I am using [this](https://www.bennish.net/web-notifications.html) to test browser notifications.

**Comment by Sweets** [comment]
Your guess isn't so far misplaced. It should be fine now, don't know why I didn't put `actions` as a capability during the rewrite.

Let me know.

**Comment by vredesbyyrd** [comment]
Yup, all good now.
