### ISSUE TITLE
JSON output: summary and body process `\n` differently (intentional?)

### ISSUE THREAD

**Issue by alnj** [Sweets/tiramisu#7]
Not sure if this is intentional, but `\n` characters are printed literally in the summary whilst in body they turn into new lines.

```sh
$ tiramisu &
$ notify-send "summary line 1\nsummary line 2" "body line 1\nbody line 2"
{ "app_name": "notify-send", "app_icon": "", "replaces_id": 0, "timeout": -1, "summary": "summary line 1\nsummary line 2", "body": "body line 1
body line 2" }
```

Perhaps summaries are meant to be one line always? That would make sense.

**Comment by Sweets** [comment]
In my testing, I did not get the same results as you did. Also, tiramisu does not do any processing other than escaping double quotes when creating the JSON. So this is something that `notify-send` is doing.

Rather than using the line-feed, you can see the difference when using

```
notify-send "summary line 1
summary line 2" "body line 1
body line 2"
```

It's intentional that new-lines are left in when being printed.
